### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by 0x0L** [conda-forge/theano-feedstock#1]
Hello,

When conda is installed as root, I noticed a minor issue with file permissions:

```
ls -la /opt/conda/lib/python3.5/site-packages/Theano-0.8.2-py3.5.egg-info/
total 56
drwxr-xr-x   2 root root  4096 Aug 18 18:56 .
drwxr-xr-x 208 root root  4096 Aug 18 18:56 ..
-rw-r-----   2 root root 11440 Aug  4 22:03 PKG-INFO
-rw-r-----   2 root root 19460 Aug  4 22:03 SOURCES.txt
-rw-r-----   2 root root     1 Aug  4 22:03 dependency_links.txt
-rw-r-----   2 root root    47 Apr 21 12:04 pbr.json
-rw-r-----   2 root root   112 Aug  4 22:03 requires.txt
-rw-r-----   2 root root     7 Aug  4 22:03 top_level.txt
```

and likewise in /opt/conda/lib/python3.5/site-packages/theano and /opt/conda/pkgs.

Probably caused by a wrongly set umask

ping @jakirkham

**Comment by jakirkham** [comment]
Sorry for the long delay. This apparently got buried in the noise.

Guessing this is on Linux. Could you please provide some more details about your setup?

**Comment by jakirkham** [comment]
FWIW I see a similar issue installed under a normal user on my Mac. So I don't think it is unique to our Linux/Docker build (my initial suspicion), but might be something funny with `conda-build`. Going to try to reproduce it locally and see if it narrows down to that.

**Comment by jakirkham** [comment]
cc @davidslac

**Comment by jakirkham** [comment]
I recently tried to build this with a new version of the docker image that we are working on that has a standard (non-elevated) user. It seems that doesn't fix it either.

**Comment by jakirkham** [comment]
Just downloaded the tarball for the [current release](https://pypi.python.org/pypi/Theano/0.8.2) and it appears this has the bad permissions in its own included `Theano.egg-info` directory. I think we should be able to pretty safely remove it before installing. Will raise this to upstream's attention first to see if there is some reason for including it.

**Comment by jakirkham** [comment]
Please see issue ( https://github.com/Theano/Theano/issues/4999 ). Will keep this open until we can come up with some satisfactory fix for our package.

**Comment by 0x0L** [comment]
@jakirkham Thanks for tracking this down 👍 

I didn't check the PyPi package bc it installed with correct perms with pip so I assumed it was fine

**Comment by jakirkham** [comment]
Of course. 😄  Sorry I didn't get to it sooner. 😞

Interesting. So I suppose we could change our install to use `pip`. Was thinking about trying that option too. Will wait for the moment though and see what upstream wants to do about it.

**Comment by davidslac** [comment]
Thanks for working on this! I don't know enough about pip vs setup.py, 
but it would be great to keep things like easy_install path 
manipulations out of conda installations - I don't remember what 
conda-forge theano feedstock does, but things like setup.py with 
externally managed options seem to help, I'm sure you all know more

**Comment by joelhullcio** [comment]
The goal is to be sure that all the files in the egg-info directory have read permissions for all users (o+r).  If not then only the user that installed the package will be able to create conda envs.  Be sure you to use the latest version of conda-build and that may just fix the issue for you.

**Comment by jakirkham** [comment]
As stated before, this is an upstream issue ( https://github.com/Theano/Theano/issues/4999 ). Please ping them to make a post release that fixes this issue and then we can package that.

**Comment by jakirkham** [comment]
I don't know if I will have time to do this myself, but would be willing to merge a PR that provides a fix like the one described [here]( https://github.com/Theano/Theano/issues/4999#issuecomment-253574589 ).

**Comment by jakirkham** [comment]
Closing as upstream has fixed this.
