### ISSUE TITLE
Test theano.gpuarray import

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/theano-feedstock#15]
We weren't testing the import of `theano.gpuarray` or anything underneath it (e.g. `theano.gpuarray.linalg`). Seems a bug, fixed in PR ( https://github.com/conda-forge/theano-feedstock/pull/14 ), snuck into the package because of this. We should start testing these imports as well (if possible).

cc @dougalsutherland

**Comment by jakirkham** [comment]
This import is gone as of `theano` version `1.0.0`. So closing this out.

**Comment by nouiz** [comment]
Those import still exists in Theano 1.0.0. this is the new GPU backend.

**Comment by jakirkham** [comment]
Sorry. We can reopen.

That said, I’m not sure what we can do on this without some sort of GPU backend present. Any suggestions?

**Comment by nouiz** [comment]
It can be imported even if there is no GPU, it is better. It will do some
check like syntax check. Can you have this line added as a test?

python -c "import theano.gpuarray"

**Comment by jakirkham** [comment]
Sure, we can add it. Though are we able to import `theano.gpuarray.linalg` without a GPU?

**Comment by nouiz** [comment]
Yes. I just tested it and it work. We need that those module are importable
even if we can't use the GPU, so if it start failing, we absolutly need to
fix it.
