### ISSUE TITLE
permission error with theano feedstock

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/theano-feedstock#2]
@davidslac commented on [Tue Sep 20 2016](https://github.com/conda-forge/feedstocks/issues/7)

I installed theano from conda-forge, into a centrally installed miniconda. As a user who does not have read/write access, ipython will not load when it tries to read egg files in site packages, I get the error

```
OError: [Errno 13] Permission denied: '/central/install/miniconda2/envs/ana/lib/python2.7/site-packages/Theano-0.8.2-py2.7.egg-info/PKG-INFO'
```

---

@jakirkham commented on [Tue Sep 20 2016](https://github.com/conda-forge/feedstocks/issues/7#issuecomment-248307977)

Thanks for the bug report, @davidslac. As this is pertinent only to the [theano feedstock](https://github.com/conda-forge/theano-feedstock), I'm going to move this issue over there.

**Comment by jakirkham** [comment]
Let's continue the discussion over here, @davidslac.

**Comment by davidslac** [comment]
Wait, I might have been installing a package I built locally that had problems, when I thought I was installing the conda-forge package, I'm going to redo things, will update, assume no problem for now

**Comment by davidslac** [comment]
I retested, there are a number of files in the conda=forge 0.8.2 theano that are installed as group readable, but not other/world readable. These are the only such files installed this way - everything else is picking up the other readable. I guess that must come from how the filesystem was setup for this directory. For instance

site-packages/Theano-0.8.2-py2.7.egg-info/PKG-INFO

**Comment by jakirkham** [comment]
Sounds like a dup of issue ( https://github.com/conda-forge/theano-feedstock/issues/1 ) then. Closing so we can consolidate the discussion.
