### ISSUE TITLE
Theano's conda packages are not multi-environment friendly

### ISSUE THREAD

**Issue by pgunn** [conda-forge/theano-feedstock#24]
Theano violates containment by trying to write files under ~/.theano/ which makes managing multiple versions of theano difficult. If possible, conda should arrange for conda builds of theano to have its dotdir reside under the conda environment path rather than in the user's homedir.

**Comment by pgunn** [comment]
It looks like this is controlled via config.base_compiledir, as per:

http://deeplearning.net/software/theano/library/config.html

**Comment by jakirkham** [comment]
Hmm...am not convinced this is the right move. For instance users of the `keras` package in conda-forge expect it to match default behavior, which is to load the config file from the home directory.

While I can see why one might want to change the config file location for an environment, expect this will cause more surprise amongst users who are expecting the default behavior to be honored. Especially if we handle this differently between various packages in conda-forge.

Plus `conda` users are able to [customize environment variables per environment]( https://conda.io/docs/user-guide/tasks/manage-environments.html#saving-environment-variables ). So users wanting this change can easily make it.

Given this, am inclined to leave the default behavior as is.

**Comment by pgunn** [comment]
Fair enough; I understand there are competing interests here.
