### ISSUE TITLE
Does anyone have any objections to bumping this up to 0.9.0dev?

### ISSUE THREAD

**Issue by springcoil** [conda-forge/theano-feedstock#5]
Hi in PyMC3 - we depend upon 0.9.0dev - do we need to wait until this becomes the full release to bump this up?

**Comment by jakirkham** [comment]
So it would need to go in a `dev` branch. Also it would be labeled so as not to be in `main`. This is all doable and could still be used in your feedstock.

Could you provide some more insight about why the dev version is needed?

**Comment by springcoil** [comment]
Well http://deeplearning.net/software/theano_versions/dev/install.html is needed for the newest version of PyMC3 Release Candidate 6 for Python 3.6 on Windows, also there's been some improvements to our ADVI algorithm that don't work without some of the changes in the dev version of Theano. For example in 0.8.2 of Theano we'll get nans and in the dev version of theano we'll get very small integers. It's an edge case, but one that we've built our software around.

**Comment by abergeron** [comment]
This is moot since the package was updated to the 0.9 release.
